--- 
- hosts: localhost 
  connection: local 
  gather_facts: false 
  vars_files:
  - /root/ansible_vsphere_template/creds.txt 



  tasks: 
  - name: Create a VM from a template 
    vmware_guest: 
      hostname: vca70.eveng.dev 
      username: "{{username}}" 
      password: "{{password}}" 
      validate_certs: no 
      datacenter: NSXT 
      folder: VRF_VMs 
      cluster: Prod-Cluster 
      name: "{{item}}" 
      state: poweredon 
      guest_id: ubuntu64Guest 
      template: ubuntu2204-template-100gb-thin 
      disk: 
      - size_gb: "{{ lookup('csvfile', '{{item}} file=vms.csv delimiter=; col=3') }}" 
        type: thin 
        datastore: "{{ lookup('csvfile', '{{item}} file=vms.csv delimiter=; col=4') }}"
      hardware: 
        memory_mb: 8192
        num_cpus: 1 
      networks: 
      - name: "{{ lookup('csvfile', '{{item}} file=vms.csv delimiter=; col=5') }}" 
        ip: "{{ lookup('csvfile', '{{item}} file=vms.csv delimiter=; col=6') }}"
        netmask: "{{ lookup('csvfile', '{{item}} file=vms.csv delimiter=; col=7') }}"
        gateway: "{{ lookup('csvfile', '{{item}} file=vms.csv delimiter=; col=8') }}"
      customization: 
        domain: eveng.dev

    with_items:
    - testvm1
    - testvm2
    - testvm3
    - testvm4
    - testvm5
