--- 
- hosts: localhost 
  connection: local 
  gather_facts: false 
  vars_files:
  - /root/ansible_vsphere_template/creds.txt 



  tasks: 
  - name: Create a VM from a template 
    vmware_guest: 
      hostname: vca70.eveng.dev 
      username: "{{username}}" 
      password: "{{password}}" 
      validate_certs: no 
      datacenter: NSXT 
      folder: VRF_VMs 
      cluster: Prod-Cluster 
      name: "{{item}}" 
      state: poweredon 
      guest_id: ubuntu64Guest 
      template: ubuntu2204-template-100gb-thin 
      networks: 
      - name: "{{ lookup('csvfile', '{{item}} file=vms.csv delimiter=; col=3') }}" 
        ip: "{{ lookup('csvfile', '{{item}} file=vms.csv delimiter=; col=4') }}"
        netmask: "{{ lookup('csvfile', '{{item}} file=vms.csv delimiter=; col=5') }}"
        gateway: "{{ lookup('csvfile', '{{item}} file=vms.csv delimiter=; col=6') }}"

    with_items:
    - testvm6
    - testvm7
    - testvm8
    - testvm9
    - testvm10
