--- 
- hosts: localhost 
  connection: local 
  gather_facts: false 

  tasks: 
  - name: Create a VM from a template 
    vmware_guest: 
      hostname: vca70.eveng.dev 
      username: "administrator@vsphere.local" 
      password: "VMwareVca!2345" 
      validate_certs: no 
      datacenter: NSXT 
      folder: VRF_VMs 
      cluster: Prod-Cluster 
      name: "{{item}}" 
      state: poweredon 
      guest_id: ubuntu64Guest 
      template: ubuntu2204-template-100gb-thin 
      networks: 
      - name: "t1-vrfa-segment" 
        ip: "192.168.10.10"
        netmask: "255.255.255.0"
        gateway: "192.168.10.1"

    with_items:
    - testvm6
