---
- name: Deploy VMs from Ubuntu template using data from CSV
  hosts: localhost
  gather_facts: no
  vars_prompt:
        - name: "datacenter"
          private: no
          prompt: "Enter datacenter name"
        - name: "cluster_name"
          private: no
          prompt: "Enter cluster name"
        - name: "folder_name"
          private: no
          prompt: "Enter VM folder name"
  tasks:
    - name: Read VM data from CSV
      read_csv:
        path: ./vms.csv
        fieldnames:
          - Vmname
          - diskSize
          - dataStoreName
          - PortGroupName
          - ip
          - subnet_mask
          - default_gateway
      register: csv_data

    - name: Deploy VMs from Ubuntu template
      vmware_guest:
        hostname: "vca70.eveng.dev"
        username: "administrator@vsphere.local"
        password: "VMware!2345"
        validate_certs: no
        datacenter: "{{ datacenter }}"
        cluster: "{{ cluster_name }}"
        folder: "{{ folder_name }}"
        name: "{{ item.Vmname }}"
        state: present
        template: "Ubuntu-2204-Template-100GB-Thin" # Name of your Ubuntu template VM
        disk:
          - size_gb: "{{ (item.diskSize|int) }}"
            type: thin
            datastore: "{{ item.dataStoreName }}"
        networks:
          - name: "{{ item.PortGroupName }}"
            ip: "{{ item.ip }}"
            netmask: "{{ item.subnet_mask }}"
            gateway: "{{ item.default_gateway }}"
            type: "static"
        customization:
          hostname: "{{ item.Vmname }}"
      loop: "{{ csv_data.list }}"
      delegate_to: localhost
