---
- name: Deploy VMs from Ubuntu template using data from CSV
  hosts: localhost
  gather_facts: no
  vars_prompt:
        - name: "vcenter_hostname"
          prompt: "Enter vCenter hostname"
        - name: "vcenter_username"
          prompt: "Enter vCenter username"
        - name: "vcenter_password"
          prompt: "Enter vCenter password"
        - name: "datacenter"
          prompt: "Enter datacenter name"
        - name: "cluster_name"
          prompt: "Enter cluster name"
        - name: "folder_name"
          prompt: "Enter VM folder name"
        - name: "datastore"
          prompt: "Enter datastore name"
        - name: "network_name"
          prompt: "Enter network name"
  tasks:
    - name: Read VM data from CSV
      read_csv:
        path: ./vms.csv
        fieldnames:
          - name
          - ip
          - subnet_mask
          - default_gateway
          - disk_size
      register: csv_data

    - name: Deploy VMs from Ubuntu template
      vmware_guest:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: no
        datacenter: "{{ datacenter }}"
        cluster: "{{ cluster_name }}"
        folder: "/{{ datacenter }}/vm/{{ folder_name }}"
        name: "{{ item.name }}"
        state: present
        template: "Ubuntu_Template_VM" # Name of your Ubuntu template VM
        disk:
          - size_gb: "{{ (item.disk_size|int / 1024)|int }}"
            type: thin
            datastore: "{{ datastore }}"
        networks:
          - name: "{{ network_name }}"
            ip: "{{ item.ip }}"
            netmask: "{{ item.subnet_mask }}"
            gateway: "{{ item.default_gateway }}"
            type: "static"
        customization:
          hostname: "{{ item.name }}"
      loop: "{{ csv_data.list }}"
      delegate_to: localhost
