--- 
- hosts: all 
  connection: local 
  gather_facts: false 
  vars_files:
  - /myproject/ansible/creds.yml 



  tasks: 
  - name: Create a VM from a template 
    vmware_guest: 
      hostname: vca70.eveng.dev 
      username: "{{username}}" 
      password: "{{password}}" 
      validate_certs: no 
      datacenter: NSX 
      folder: VRF_VMs 
      cluster: Prod-Compute 
      name: "{{item}}" 
      state: poweredon 
      guest_id: ubuntu64Guest 
      template: Ubuntu-2204-Template-100-Thin 
      disk: 
      - size_gb: "{{ lookup('csvfile', '{{item}} file=vms.csv delimiter=; col=3') }}" 
        type: thin 
        datastore: "{{ lookup('csvfile', '{{item}} file=vms.csv delimiter=; col=4') }}"
      hardware: 
        memory_mb: "{{ lookup('csvfile', '{{item}} file=vms.csv delimiter=; col=2') }}"
        num_cpus: "{{ lookup('csvfile', '{{item}} file=vms.csv delimiter=; col=1') }}" 
      networks: 
      - name: "{{ lookup('csvfile', '{{item}} file=vms.csv delimiter=; col=5') }}" 
        ip: "{{ lookup('csvfile', '{{item}} file=vms.csv delimiter=; col=6') }}"
        netmask: "{{ lookup('csvfile', '{{item}} file=vms.csv delimiter=; col=7') }}"
        gateway: "{{ lookup('csvfile', '{{item}} file=vms.csv delimiter=; col=8') }}"
      customization: 
        domain: eveng.dev 
        dns_servers: 
        - 192.168.1.3

    with_items:
    - testvm1
    - testvm2
    - testvm3
    - testvm4
    - testvm5
