---
- name: Create a VM from template and customize
  hosts: localhost
  connection: local
  gather_facts: no
  vars:
    base_ip_address: "192.168.1."
    start_index: 111
    end_index: 113
  tasks:
  - name: Create VMs
    vmware_guest:
      hostname: vca70.eveng.dev
      username: administrator@vsphere.local
      password: Admin!2345
      validate_certs: False
      datacenter: NSX-T
      folder: VRF-VMs
      name: "vm-vrf-{{ item }}"
      state: poweredon
      template: Ubuntu-2204-Template-100GB-Thin
      esxi_hostname: pcs-esxi1.eveng.dev
      disk:
      - size_gb: 100
        type: thin
        datastore: esxi1
      hardware:
        memory_mb: 4096
        num_cpus: 2
        num_cpu_cores_per_socket: 1
        scsi: paravirtual
        memory_reservation_lock: no
        #mem_limit: 8096
        mem_reservation: 0
        #cpu_limit: 8096
        cpu_reservation: 0
        hotadd_cpu: True
        hotremove_cpu: True
        hotadd_memory: True
        #version: 19 # Hardware version of virtual machine
        boot_firmware: "efi"
      networks:
      - name: DPortGroup
      customization:
       hostname: "vm-vrf-{{ item }}"
       dns_servers: 
        - 192.168.1.3
       ip_settings:
        ip: "{{ (base_ip_address | ipmath('+(item)')) }}"
        netmask: 255.255.255.0
        gateway: 192.168.1.1
      wait_for_ip_address: no
    delegate_to: localhost
    register: deploy
    loop: "{{ range(start_index, end_index) }}"