---
- name: Create a VM from template and customize
  hosts: localhost
  gather_facts: no
  var_files:
    variables.yml
  tasks:
    - name: Create VMs
      vmware_guest:
        hostname: vca70.eveng.dev
        username: administrator@vsphere.local
        password: VMwareVca!2345
        validate_certs: false
        datacenter: NSXT
        folder: Templates
        state: poweredon
        cluster: Prod-Cluster
        template: ubuntu2204-template-100gb-thin
        name: "{{ item }}"
        networks:
          - name: t1-vrfa-segment
      loop: "{{ servers }}"
        
        #delegate_to: localhost
      
