---
- name: Create a VM from template and customize
  hosts: localhost
  connection: local
  gather_facts: no
  vars:
    ip_base: "192.168.1."
    starting_index: 115
    num_vms: 2
    hostname: vm-vrf
  tasks:
  - name: Create VMs
    vmware_guest:
      hostname: vca70.eveng.dev
      username: administrator@vsphere.local
      password: Admin!2345
      validate_certs: False
      datacenter: NSX-T
      folder: VRF-VMs
      name: "{{ hostname }}{{ item }}"
      state: poweredon
      template: Ubuntu-2204-Template-100GB-Thin
      esxi_hostname: pcs-esxi1.eveng.dev
      disk:
      - size_gb: 100
        type: thin
        datastore: esxi1
      hardware:
        memory_mb: 4096
        num_cpus: 2
        num_cpu_cores_per_socket: 1
        scsi: paravirtual
        memory_reservation_lock: no
        #mem_limit: 8096
        mem_reservation: 0
        #cpu_limit: 8096
        cpu_reservation: 0
        hotadd_cpu: True
        hotremove_cpu: True
        hotadd_memory: True
        #version: 19 # Hardware version of virtual machine
        boot_firmware: "efi"     
      networks:
      - name: DPortGroup
        hostname: "{{ hostname }}{{ item }}"
        dns_servers: 
        - 192.168.1.3
        ip: "{{ ip_base }}{{ ipmath(1)}}"
        netmask: 255.255.255.0
        gateway: 192.168.1.1
        with_sequence: start={{ starting_index }} count={{ num_vms }}
      wait_for_ip_address: no
    delegate_to: localhost
    register: deploy
    with_sequence: start={{ starting_index }} count={{ num_vms }}
    