---
- name: Create a VM from template and customize
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:
  - name: Read VM data from CSV
      read_csv:
        path: /home/ubuntu/ansible/create_vms_from_csv/vms.csv
        delimiter: ','
      register: csv_data
  - name: Create VMs
    vmware_guest:
      hostname: vca70.eveng.dev
      username: administrator@vsphere.local
      password: VMware!2345
      validate_certs: False
      datacenter: NSX
      folder: Templates
      name: "{{ hostname }}{{ item }}"
      state: poweredon
      cluster: Prod-Compute
      template: Ubuntu-2204-Template-100GB-Thin
      name: "{{ item.vm_name }}"
        networks:
          - name: prod-vds-mgt
            ip: "{{ item.ip_address }}"
            gateway: "{{ item.gateway }}"
            netmask: "255.255.255.0" # Adjust as needed
            dns_servers: 
              - "{{ item.dns_server }}"
      loop: "{{ csv_data.list }}"
      wait_for_ip_address: no
    delegate_to: localhost
    
