---
- name: Create a VM from template and customize
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Read VM data from CSV
      read_csv:
        path: /root/ansible_vsphere_template/vms.csv
        delimiter: ','
      register: csv_data
    - name: Create VMs
      vmware_guest:
        hostname: vca70.eveng.dev
        username: administrator@vsphere.local
        password: VMware!2345
        validate_certs: false
        datacenter: NSX
        folder: Templates
        name: "{{ hostname }}{{ item }}"
        state: poweredon
        cluster: Prod-Cluster
        template: Ubuntu-2204-Template-100GB-Thin
        name: "{{ item.vm_name }}"
        networks:
          - name: prod-vds-mgt
            type: static
            ip: "{{ item.ip_address }}"
            gateway: "{{ item.gateway }}"
            netmask: "255.255.255.0" # Adjust as needed
            dns_servers: 
                - "{{ item.dns_server }}"
        wait_for_ip_address: false
      loop: "{{ csv_data.list }}"
        
        #delegate_to: localhost
      
