---
- name: Create a VM from template and customize
  hosts: localhost
  connection: local
  gather_facts: no

  tasks:
  - name: Create VM for vm-vrf2
    vmware_guest:
      hostname: vca70.eveng.dev
      username: administrator@vsphere.local
      password: Admin!2345
      validate_certs: False
      datacenter: NSX-T
      folder: VRF-VMs
      name: vm-vrf2
      state: poweredon
      template: Ubuntu-2204-Template-100GB-Thin
      esxi_hostname: pcs-esxi1.eveng.dev
      disk:
      - size_gb: 100
        type: thin
        datastore: esxi1
      hardware:
        memory_mb: 4096
        num_cpus: 2
        num_cpu_cores_per_socket: 1
        scsi: paravirtual
        memory_reservation_lock: no
        #mem_limit: 8096
        mem_reservation: 0
        #cpu_limit: 8096
        cpu_reservation: 0
        hotadd_cpu: True
        hotremove_cpu: True
        hotadd_memory: True
        #version: 19 # Hardware version of virtual machine
        boot_firmware: "efi"
      networks:
      - name: DPortGroup
        ip: 192.168.1.106
        netmask: 255.255.255.0
        gateway: 192.168.1.1
        dns_servers:
        - 192.168.1.3
      wait_for_ip_address: no
    delegate_to: localhost
    register: deploy

    tasks:
  - name: Create VM for vm-vrf3
    vmware_guest:
      hostname: vca70.eveng.dev
      username: administrator@vsphere.local
      password: Admin!2345
      validate_certs: False
      datacenter: NSX-T
      folder: VRF-VMs
      name: vm-vrf3
      state: poweredon
      template: Ubuntu-2204-Template-100GB-Thin
      esxi_hostname: pcs-esxi1.eveng.dev
      disk:
      - size_gb: 100
        type: thin
        datastore: esxi1
      hardware:
        memory_mb: 4096
        num_cpus: 2
        num_cpu_cores_per_socket: 1
        scsi: paravirtual
        memory_reservation_lock: no
        #mem_limit: 8096
        mem_reservation: 0
        #cpu_limit: 8096
        cpu_reservation: 0
        hotadd_cpu: True
        hotremove_cpu: True
        hotadd_memory: True
        #version: 19 # Hardware version of virtual machine
        boot_firmware: "efi"
      networks:
      - name: DPortGroup
        ip: 192.168.1.107
        netmask: 255.255.255.0
        gateway: 192.168.1.1
        dns_servers:
        - 192.168.1.3
      wait_for_ip_address: no
    delegate_to: localhost
    register: deploy

    tasks:
  - name: Create VM for vm-vrf4
    vmware_guest:
      hostname: vca70.eveng.dev
      username: administrator@vsphere.local
      password: Admin!2345
      validate_certs: False
      datacenter: NSX-T
      folder: VRF-VMs
      name: vm-vrf4
      state: poweredon
      template: Ubuntu-2204-Template-100GB-Thin
      esxi_hostname: pcs-esxi1.eveng.dev
      disk:
      - size_gb: 100
        type: thin
        datastore: esxi1
      hardware:
        memory_mb: 4096
        num_cpus: 2
        num_cpu_cores_per_socket: 1
        scsi: paravirtual
        memory_reservation_lock: no
        #mem_limit: 8096
        mem_reservation: 0
        #cpu_limit: 8096
        cpu_reservation: 0
        hotadd_cpu: True
        hotremove_cpu: True
        hotadd_memory: True
        #version: 19 # Hardware version of virtual machine
        boot_firmware: "efi"
      networks:
      - name: DPortGroup
        ip: 192.168.1.108
        netmask: 255.255.255.0
        gateway: 192.168.1.1
        dns_servers:
        - 192.168.1.3
      wait_for_ip_address: no
    delegate_to: localhost
    register: deploy

    tasks:
  - name: Create VM for vm-vrf5
    vmware_guest:
      hostname: vca70.eveng.dev
      username: administrator@vsphere.local
      password: Admin!2345
      validate_certs: False
      datacenter: NSX-T
      folder: VRF-VMs
      name: vm-vrf5
      state: poweredon
      template: Ubuntu-2204-Template-100GB-Thin
      esxi_hostname: pcs-esxi1.eveng.dev
      disk:
      - size_gb: 100
        type: thin
        datastore: esxi1
      hardware:
        memory_mb: 4096
        num_cpus: 2
        num_cpu_cores_per_socket: 1
        scsi: paravirtual
        memory_reservation_lock: no
        #mem_limit: 8096
        mem_reservation: 0
        #cpu_limit: 8096
        cpu_reservation: 0
        hotadd_cpu: True
        hotremove_cpu: True
        hotadd_memory: True
        #version: 19 # Hardware version of virtual machine
        boot_firmware: "efi"
      networks:
      - name: DPortGroup
        ip: 192.168.1.109
        netmask: 255.255.255.0
        gateway: 192.168.1.1
        dns_servers:
        - 192.168.1.3
      wait_for_ip_address: no
    delegate_to: localhost
    register: deploy

    tasks:
  - name: Create VM for vm-vrf6
    vmware_guest:
      hostname: vca70.eveng.dev
      username: administrator@vsphere.local
      password: Admin!2345
      validate_certs: False
      datacenter: NSX-T
      folder: VRF-VMs
      name: vm-vrf6
      state: poweredon
      template: Ubuntu-2204-Template-100GB-Thin
      esxi_hostname: pcs-esxi1.eveng.dev
      disk:
      - size_gb: 100
        type: thin
        datastore: esxi1
      hardware:
        memory_mb: 4096
        num_cpus: 2
        num_cpu_cores_per_socket: 1
        scsi: paravirtual
        memory_reservation_lock: no
        #mem_limit: 8096
        mem_reservation: 0
        #cpu_limit: 8096
        cpu_reservation: 0
        hotadd_cpu: True
        hotremove_cpu: True
        hotadd_memory: True
        #version: 19 # Hardware version of virtual machine
        boot_firmware: "efi"
      networks:
      - name: DPortGroup
        ip: 192.168.1.110
        netmask: 255.255.255.0
        gateway: 192.168.1.1
        dns_servers:
        - 192.168.1.3
      wait_for_ip_address: no
    delegate_to: localhost
    register: deploy

    tasks:
  - name: Create VM for vm-vrf7
    vmware_guest:
      hostname: vca70.eveng.dev
      username: administrator@vsphere.local
      password: Admin!2345
      validate_certs: False
      datacenter: NSX-T
      folder: VRF-VMs
      name: vm-vrf7
      state: poweredon
      template: Ubuntu-2204-Template-100GB-Thin
      esxi_hostname: pcs-esxi1.eveng.dev
      disk:
      - size_gb: 100
        type: thin
        datastore: esxi1
      hardware:
        memory_mb: 4096
        num_cpus: 2
        num_cpu_cores_per_socket: 1
        scsi: paravirtual
        memory_reservation_lock: no
        #mem_limit: 8096
        mem_reservation: 0
        #cpu_limit: 8096
        cpu_reservation: 0
        hotadd_cpu: True
        hotremove_cpu: True
        hotadd_memory: True
        #version: 19 # Hardware version of virtual machine
        boot_firmware: "efi"
      networks:
      - name: DPortGroup
        ip: 192.168.1.111
        netmask: 255.255.255.0
        gateway: 192.168.1.1
        dns_servers:
        - 192.168.1.3
      wait_for_ip_address: no
    delegate_to: localhost
    register: deploy

    tasks:
  - name: Create VM for vm-vrf8
    vmware_guest:
      hostname: vca70.eveng.dev
      username: administrator@vsphere.local
      password: Admin!2345
      validate_certs: False
      datacenter: NSX-T
      folder: VRF-VMs
      name: vm-vrf8
      state: poweredon
      template: Ubuntu-2204-Template-100GB-Thin
      esxi_hostname: pcs-esxi1.eveng.dev
      disk:
      - size_gb: 100
        type: thin
        datastore: esxi1
      hardware:
        memory_mb: 4096
        num_cpus: 2
        num_cpu_cores_per_socket: 1
        scsi: paravirtual
        memory_reservation_lock: no
        #mem_limit: 8096
        mem_reservation: 0
        #cpu_limit: 8096
        cpu_reservation: 0
        hotadd_cpu: True
        hotremove_cpu: True
        hotadd_memory: True
        #version: 19 # Hardware version of virtual machine
        boot_firmware: "efi"
      networks:
      - name: DPortGroup
        ip: 192.168.1.112
        netmask: 255.255.255.0
        gateway: 192.168.1.1
        dns_servers:
        - 192.168.1.3
      wait_for_ip_address: no
    delegate_to: localhost
    register: deploy

    tasks:
  - name: Create VM for vm-vrf9
    vmware_guest:
      hostname: vca70.eveng.dev
      username: administrator@vsphere.local
      password: Admin!2345
      validate_certs: False
      datacenter: NSX-T
      folder: VRF-VMs
      name: vm-vrf9
      state: poweredon
      template: Ubuntu-2204-Template-100GB-Thin
      esxi_hostname: pcs-esxi1.eveng.dev
      disk:
      - size_gb: 100
        type: thin
        datastore: esxi1
      hardware:
        memory_mb: 4096
        num_cpus: 2
        num_cpu_cores_per_socket: 1
        scsi: paravirtual
        memory_reservation_lock: no
        #mem_limit: 8096
        mem_reservation: 0
        #cpu_limit: 8096
        cpu_reservation: 0
        hotadd_cpu: True
        hotremove_cpu: True
        hotadd_memory: True
        #version: 19 # Hardware version of virtual machine
        boot_firmware: "efi"
      networks:
      - name: DPortGroup
        ip: 192.168.1.113
        netmask: 255.255.255.0
        gateway: 192.168.1.1
        dns_servers:
        - 192.168.1.3
      wait_for_ip_address: no
    delegate_to: localhost
    register: deploy

    tasks:
  - name: Create VM for vm-vrf10
    vmware_guest:
      hostname: vca70.eveng.dev
      username: administrator@vsphere.local
      password: Admin!2345
      validate_certs: False
      datacenter: NSX-T
      folder: VRF-VMs
      name: vm-vrf10
      state: poweredon
      template: Ubuntu-2204-Template-100GB-Thin
      esxi_hostname: pcs-esxi1.eveng.dev
      disk:
      - size_gb: 100
        type: thin
        datastore: esxi1
      hardware:
        memory_mb: 4096
        num_cpus: 2
        num_cpu_cores_per_socket: 1
        scsi: paravirtual
        memory_reservation_lock: no
        #mem_limit: 8096
        mem_reservation: 0
        #cpu_limit: 8096
        cpu_reservation: 0
        hotadd_cpu: True
        hotremove_cpu: True
        hotadd_memory: True
        #version: 19 # Hardware version of virtual machine
        boot_firmware: "efi"
      networks:
      - name: DPortGroup
        ip: 192.168.1.114
        netmask: 255.255.255.0
        gateway: 192.168.1.1
        dns_servers:
        - 192.168.1.3
      wait_for_ip_address: no
    delegate_to: localhost
    register: deploy

    