---
- name: Create a VM from template and customize
  hosts: localhost
  connection: local
  gather_facts: no
  vars:
    ip_base: 192.168.1.
    starting_index: 50
    num_vms: 2
    hostname: vm-vrf
  tasks:
  - name: Create VMs
    vmware_guest:
      hostname: vca70.eveng.dev
      username: administrator@vsphere.local
      password: VMware!2345
      validate_certs: False
      datacenter: NSX
      folder: Templates
      name: "{{ hostname }}{{ item }}"
      state: poweredon
      cluster: Prod-Compute
      template: Ubuntu-2204-Template-100GB-Thin
      networks:
      - name: prod-vds-mgt
        hostname: "{{ hostname }}{{ item }}"
        dns_servers: 
        - 192.168.1.3
        ip: "{{ ip_base }}{{ starting_index + ansible_loop.index0 }}"
        netmask: 255.255.255.0
        gateway: 192.168.1.2
      wait_for_ip_address: no
    delegate_to: localhost
    register: deploy
    with_sequence: start={{ starting_index }} count={{ num_vms }}
    loop_control:
      extended: true
    
