- name: Create VMs with increasing IP address
  hosts: localhost
  connection: local
  vars:
    ip_base: "10.0.0."    # the first three octets of the IP address
    starting_index: 1     # the starting index for the last octet of the IP address
    num_vms: 5            # the number of VMs to create
  tasks:
    - name: Create VM
      vmware_guest:
        hostname: vcenter.example.com
        username: myuser
        password: mypass
        validate_certs: no
        datacenter: mydatacenter
        name: "{{ item }}"
        state: poweredon
        hardware:
          memory_mb: 2048
          num_cpus: 2
          scsi: paravirtual
        networks:
          - name: VM Network
            ip: "{{ ip_base }}{{ starting_index + (item | int) }}"
            netmask: 255.255.255.0
            gateway: 10.0.0.1
      with_sequence: start={{ starting_index }} count={{ num_vms }}
