- hosts: localhost
  gather_facts: false
  connection: local
  vars:
    start_ip: 10.10.10.10

  tasks:
    - set_fact:
        next_ip: "{{ start_ip|ipmath(1) }}"
    - debug:
        msg: "Next ip of {{ start_ip }} is: {{ next_ip }}"