---
- name: Increase IP address by 1 with ipmath
  hosts: localhost
  vars:
    num_ips: 5
    starting_ip: "192.168.1.1"
  tasks:
    - name: Generate list of IPs using ipmath
      debug:
        msg: "{{ (starting_ip | ipmath('+(item)')) }}"
      with_sequence: start=0 end={{ num_ips + (item) }}