- name: Generate IP addresses
  hosts: localhost
  gather_facts: no
  vars:
    ip_base: "10.0.0."    # the first three octets of the IP address
    starting_index: 1     # the starting index for the last octet of the IP addresses
    num_vms: 5            # the number of VMs to create
    hostname: vm-vrf-
  tasks:
    - name: Print IP addresses
      debug:
        msg: "{{ ip_base }}{{ starting_index + (item | int) }}"
      with_sequence: start={{ starting_index }} count={{ num_vms }}
