- name: Generate IP addresses
  hosts: localhost
  gather_facts: no
  vars:
    base_ip_address: "192.168.1."
    hostname: "vm-vrf-"
    start_index: 110
    end_index: 120
  tasks:
    - name: Print IP addresses
      debug:
        msg: "{{ base_ip_address }}{{ item }}"
      loop: "{{ range(start_index, end_index) }}"
    - name: Print hostname 
      debug:
        msg: "{{ hostname }}{{ item }}"
      loop: "{{ range(start_index, end_index) }}"