- name: Generate IP addresses
  hosts: localhost
  gather_facts: no
  vars:
    base_ip_address: "192.168.1."
    start_index: 3
    end_index: 5
  tasks:
    - name: Print IP addresses
      debug:
        msg: "{{ base_ip_address }}{{ item }}"
      loop: "{{ range(start_index, end_index) }}"