---
- name: Increase IP address by 1 with ipmath
  hosts: localhost
  vars:
    starting_ip: "192.168.1.1"
    num_ips: 5
  tasks:
    - name: Generate list of IPs using ipmath
      debug:
        msg: "{{ starting_ip|ipmath(1) }}"
      with_sequence: start=0 end={{ num_ips - 1 }}
