---
   
- name: Increase IP address by 1 with ipmath
  hosts: localhost
  vars:
    starting_ip: "192.168.1.1"
    num_vms: 5
  tasks:
    - name: Generate list of IP addresses
      set_fact:
        ip_list: "{{ range(num_vms) | map('ipmath', starting_ip, '+(item)') | list }}"
    - name: Print out a list from a fact
      debug:
      msg: "{{ list }}"
