- hosts: localhost
  vars:
    ip_address: "192.168.1.1"
    num_ips: 5
  tasks:
    - name: Increase IP address
      set_fact:
        ip_address: "{{ (ip_address.split('.')[:-1] + [ip_address.split('.')[-1]|int + loop.index]) | join('.') }}"
      debug:
        msg: "{{ ip_address }}"
      loop: "{{ range(1, num_ips) | list }}"