---
- name: Remove a VM
  hosts: localhost
  connection: local
  gather_facts: no

  tasks:
  - name: Remove power for vm-vrf1
    vmware_guest:
      hostname: vca70.eveng.dev
      username: administrator@vsphere.local
      password: Admin!2345
      validate_certs: False
      datacenter: NSX-T
      folder: VRF-VMs
      name: vm-vrf1
      state: poweredoff
    delegate_to: localhost
    register: facts
 
  - name: Remove VM for vm-vrf1
    vmware_guest:
      hostname: vca70.eveng.dev
      username: administrator@vsphere.local
      password: Admin!2345
      validate_certs: False
      datacenter: NSX-T
      folder: VRF-VMs
      name: vm-vrf1
      state: absent
    delegate_to: localhost
    register: facts

  - name: Remove power for vm-vrf10
    vmware_guest:
      hostname: vca70.eveng.dev
      username: administrator@vsphere.local
      password: Admin!2345
      validate_certs: False
      datacenter: NSX-T
      folder: VRF-VMs
      name: vm-vrf10
      state: poweredoff
    delegate_to: localhost
    register: facts

  - name: Remove VM for vm-vrf10
    vmware_guest:
      hostname: vca70.eveng.dev
      username: administrator@vsphere.local
      password: Admin!2345
      validate_certs: False
      datacenter: NSX-T
      folder: VRF-VMs
      name: vm-vrf10
      state: absent
    delegate_to: localhost
    register: facts

  - name: Remove power for vm-vrf12
    vmware_guest:
      hostname: vca70.eveng.dev
      username: administrator@vsphere.local
      password: Admin!2345
      validate_certs: False
      datacenter: NSX-T
      folder: VRF-VMs
      name: vm-vrf12
      state: poweredoff
    delegate_to: localhost
    register: facts

  - name: Remove VM for vm-vrf12
    vmware_guest:
      hostname: vca70.eveng.dev
      username: administrator@vsphere.local
      password: Admin!2345
      validate_certs: False
      datacenter: NSX-T
      folder: VRF-VMs
      name: vm-vrf12
      state: absent
    delegate_to: localhost
    register: facts