---
- name: Remove a VM
  hosts: localhost
  connection: local
  gather_facts: no

  tasks:

  - name: Remove power for vm-vrf50
    vmware_guest:
      hostname: vca70.eveng.dev
      username: administrator@vsphere.local
      password: VMware!2345
      validate_certs: False
      datacenter: NSX
      folder: Templates
      name: test19_01
      state: poweredoff
    delegate_to: localhost
    register: facts

  - name: Remove VM for vm-vrf50
    vmware_guest:
      hostname: vca70.eveng.dev
      username: administrator@vsphere.local
      password: VMware!2345
      validate_certs: False
      datacenter: NSX
      folder: Templates
      name: test19_02
      state: absent
    delegate_to: localhost
    register: facts

  - name: Remove power for vm-vrf51
    vmware_guest:
      hostname: vca70.eveng.dev
      username: administrator@vsphere.local
      password: VMware!2345
      validate_certs: False
      datacenter: NSX
      folder: Templates
      name: testvm10
      state: poweredoff
    delegate_to: localhost
    register: facts

  - name: Remove VM for vm-vrf51
    vmware_guest:
      hostname: vca70.eveng.dev
      username: administrator@vsphere.local
      password: VMware!2345
      validate_certs: False
      datacenter: NSX
      folder: Templates
      name: testvm9
      state: absent
    delegate_to: localhost
    register: facts



  - name: Remove VM for vm-vrf51
    vmware_guest:
      hostname: vca70.eveng.dev
      username: administrator@vsphere.local
      password: VMware!2345
      validate_certs: False
      datacenter: NSX
      folder: Templates
      name: testvm8
      state: absent
    delegate_to: localhost
    register: facts
    
  - name: Remove VM for vm-vrf51
    vmware_guest:
      hostname: vca70.eveng.dev
      username: administrator@vsphere.local
      password: VMware!2345
      validate_certs: False
      datacenter: NSX
      folder: Templates
      name: testvm7
      state: absent
    delegate_to: localhost
    register: facts  

  - name: Remove VM for vm-vrf51
    vmware_guest:
      hostname: vca70.eveng.dev
      username: administrator@vsphere.local
      password: VMware!2345
      validate_certs: False
      datacenter: NSX
      folder: Templates
      name: testvm6
      state: absent
    delegate_to: localhost
    register: facts  
