---
- name: Remove a VM
  hosts: localhost
  connection: local
  gather_facts: no

  tasks:

  - name: Remove power for vm-vrf-111
    vmware_guest:
      hostname: vca70.eveng.dev
      username: administrator@vsphere.local
      password: Admin!2345
      validate_certs: False
      datacenter: NSX-T
      folder: VRF-VMs
      name: vm-vrf231
      state: poweredoff
    delegate_to: localhost
    register: facts

  - name: Remove VM for vm-vr111
    vmware_guest:
      hostname: vca70.eveng.dev
      username: administrator@vsphere.local
      password: Admin!2345
      validate_certs: False
      datacenter: NSX-T
      folder: VRF-VMs
      name: vm-vrf231
      state: absent
    delegate_to: localhost
    register: facts