---
- name: Remove a VM
  hosts: localhost
  connection: local
  gather_facts: no

  tasks:
  - name: Remove VM for vm-vrf9
    vmware_guest:
      hostname: vca70.eveng.dev
      username: administrator@vsphere.local
      password: Admin!2345
      validate_certs: False
      datacenter: NSX-T
      folder: VRF-VMs
      name: vm-vrf9
      state: absent
    delegate_to: localhost
    register: facts