---
- name: add index
   hosts: localhost
   gather_facts: false
   connection: local
   
   tasks:

   - name: Use of variable
      ansible.builtin.debug:
        msg: "{{ item }}"
      with_sequence: start=1 end="{{ end_at }}"
      vars:
        - end_at: 10